using System.Runtime.InteropServices;

namespace TopSecret;

/// <summary>
/// Thin cross-platform wrapper around the OS crash-dump exclusion primitives:
/// <c>WerRegisterExcludedMemoryBlock</c> / <c>WerUnregisterExcludedMemoryBlock</c>
/// on Windows and <c>madvise(MADV_DONTDUMP)</c> / <c>madvise(MADV_DODUMP)</c> on
/// Linux and Android. Excluded ranges are omitted from the dumps those
/// facilities produce.
/// </summary>
/// <remarks>
/// <para>
/// <b>What exclusion covers — and what it does not.</b> On Windows,
/// registration affects only dumps generated by Windows Error Reporting
/// (crash dumps, <c>WerReportAddDump</c>); Task Manager dumps, ProcDump,
/// debugger <c>.dump</c>, and kernel dumps still contain the bytes. On
/// Linux/Android, <c>MADV_DONTDUMP</c> affects only the kernel's core-dump
/// path; <c>ptrace</c> readers (gcore, debuggers) still see the pages. On
/// macOS, iOS, Mac Catalyst, and browser-wasm no exclusion primitive exists;
/// calls are silent no-ops there (see <see cref="IsSupported"/>). Dump
/// exclusion is therefore a best-effort layer on top of the encrypt-at-rest
/// and wipe-on-exit guarantees, not a substitute for them.
/// </para>
/// <para>
/// <b>Windows budget.</b> WER caps the number of registered blocks
/// (register + exclude combined) at 512 per process. Sensitive buffers are
/// transient — plaintext scratch lives for one operation, build buffers until
/// commit — so typical live registrations stay in the single digits, but a
/// process holding hundreds of concurrent sensitive buffers can exhaust the
/// budget; later <see cref="TryExclude{T}"/> calls then fail and the
/// configured <see cref="ProtectedStringOptions.MemoryLockingFailureBehavior"/>
/// applies at the call site.
/// </para>
/// <para>
/// <b>Page granularity (libc targets).</b> <c>madvise</c> operates on whole
/// pages, and the requested range is page-rounded here. A pinned-object-heap
/// page can hold unrelated objects, which then drop out of core dumps too
/// (harmless for security, mildly annoying for diagnostics). Exclusion is
/// one-way on libc targets — see <see cref="TryInclude{T}"/> for why wiped
/// pages deliberately stay excluded — so a live excluded buffer can never
/// lose its exclusion to a neighbour's teardown. Hot per-operation scratch
/// additionally rents from <see cref="LockedScratchPool"/>, whose slabs are
/// excluded once at creation.
/// </para>
/// </remarks>
internal static class DumpExclusion
{
    private const int MADV_DONTDUMP = 16;
    private const int MADV_DODUMP = 17;

    private static readonly Lazy<bool> s_supported =
        new(Probe, LazyThreadSafetyMode.ExecutionAndPublication);

    /// <summary>
    /// Whether a dump-exclusion primitive is reachable on this platform.
    /// <see langword="false"/> on macOS / iOS / Mac Catalyst / browser-wasm
    /// (no primitive exists), or when the probe call failed. The probe runs
    /// at most once per process.
    /// </summary>
    public static bool IsSupported => s_supported.Value;

    /// <summary>
    /// Attempts to exclude <paramref name="buffer"/> from OS-generated crash
    /// dumps. Returns <see langword="true"/> on success, for an empty buffer,
    /// or when the platform has no exclusion primitive (not-applicable is not
    /// a failure — the caller cannot act on it and the configured policy
    /// should not fire for a capability the OS simply does not offer).
    /// Returns <see langword="false"/> only when the platform primitive
    /// exists and the call failed (e.g. WER's 512-entry budget is exhausted),
    /// so the caller can apply
    /// <see cref="ProtectedStringOptions.MemoryLockingFailureBehavior"/>.
    /// </summary>
    /// <remarks>
    /// <paramref name="buffer"/> must already be pinned (e.g., allocated via
    /// <see cref="GC.AllocateArray{T}(int, bool)"/> with <c>pinned: true</c>).
    /// </remarks>
    public static bool TryExclude<T>(T[] buffer) where T : unmanaged
    {
        if (buffer.Length == 0) return true;
        if (!IsSupported) return true;
        return TryAdvise(
            Marshal.UnsafeAddrOfPinnedArrayElement(buffer, 0),
            ByteSize(buffer),
            exclude: true);
    }

    /// <summary>
    /// Reverses a prior <see cref="TryExclude{T}"/> on Windows, returning the
    /// WER budget entry. On libc targets this is a deliberate no-op:
    /// exclusion is one-way there.
    /// </summary>
    /// <remarks>
    /// WER registrations are exact-range, so unregistering one buffer cannot
    /// touch a neighbour. <c>madvise(MADV_DODUMP)</c> is page-granular: a
    /// wiped transient buffer's re-inclusion would strip
    /// <c>MADV_DONTDUMP</c> from any still-live excluded buffer sharing the
    /// page — e.g. a wrap key allocated next to its own per-operation
    /// ephemerals loses its exclusion after the first unwrap, permanently.
    /// Leaving wiped pages excluded is the conservative direction for a
    /// security library (the cost is that core dumps omit whatever the POH
    /// later reuses those pages for). Safe to call for buffers that were
    /// never excluded; failures are not actionable and are swallowed.
    /// </remarks>
    public static void TryInclude<T>(T[] buffer) where T : unmanaged
    {
        if (buffer.Length == 0 || !IsSupported) return;
        if (!OperatingSystem.IsWindows()) return;
        TryAdvise(
            Marshal.UnsafeAddrOfPinnedArrayElement(buffer, 0),
            ByteSize(buffer),
            exclude: false);
    }

    /// <summary>
    /// Excludes an arbitrary (caller-aligned) address range. Used by
    /// <see cref="LockedScratchPool"/> for a slab's page-aligned interior.
    /// Same return contract as <see cref="TryExclude{T}"/>.
    /// </summary>
    public static bool TryExcludeRange(IntPtr addr, int size)
    {
        if (size == 0) return true;
        if (!IsSupported) return true;
        return TryAdvise(addr, (nuint)size, exclude: true);
    }

    private static nuint ByteSize<T>(T[] buffer) where T : unmanaged =>
        MemoryLocker.ByteSize(buffer);

    private static bool Probe()
    {
        // MADV_DONTDUMP/MADV_DODUMP are Linux-kernel advice values (3.4+);
        // the same numbers on other kernels mean something else or nothing,
        // and WerRegisterExcludedMemoryBlock exists only on Windows 10 /
        // Server 2016+ — so gate on the platforms explicitly rather than
        // letting the probe discover "support" by accident. macOS / iOS /
        // Mac Catalyst / browser-wasm have no primitive at all.
        if (!OperatingSystem.IsWindows() &&
            !OperatingSystem.IsLinux() &&
            !OperatingSystem.IsAndroid())
        {
            return false;
        }

        try
        {
            var probe = GC.AllocateArray<byte>(64, pinned: true);
            var addr = Marshal.UnsafeAddrOfPinnedArrayElement(probe, 0);
            var size = (nuint)probe.Length;
            // TryAdvise owns the per-platform dispatch and the exception
            // swallowing (DllNotFoundException / EntryPointNotFoundException
            // on old hosts become false) — the probe just exercises a full
            // exclude/include round trip through it.
            if (!TryAdvise(addr, size, exclude: true)) return false;
            TryAdvise(addr, size, exclude: false);
            return true;
        }
        catch
        {
            // Probing must never crash the type initializer.
            return false;
        }
    }

    private static bool TryAdvise(IntPtr addr, nuint size, bool exclude)
    {
        try
        {
            if (OperatingSystem.IsWindows())
            {
                if (exclude)
                {
                    return WerRegisterExcludedMemoryBlock(addr, (uint)size) == 0;
                }
                // Not-registered is indistinguishable from success for our
                // purposes (the entry is gone either way).
                WerUnregisterExcludedMemoryBlock(addr);
                return true;
            }

            return Madvise(addr, size, exclude ? MADV_DONTDUMP : MADV_DODUMP) == 0;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// <c>madvise</c> demands a page-aligned start address, so round the range
    /// out to page boundaries. See the type remarks for the page-granularity
    /// consequences of advising more than exactly the buffer's bytes.
    /// </summary>
    private static int Madvise(IntPtr addr, nuint size, int advice)
    {
        long page = Environment.SystemPageSize;
        long start = addr.ToInt64() & ~(page - 1);
        long end = (addr.ToInt64() + (long)size + page - 1) & ~(page - 1);
        return madvise((IntPtr)start, (nuint)(end - start), advice);
    }

    [DllImport("kernel32", ExactSpelling = true)]
    private static extern int WerRegisterExcludedMemoryBlock(IntPtr address, uint size);

    [DllImport("kernel32", ExactSpelling = true)]
    private static extern int WerUnregisterExcludedMemoryBlock(IntPtr address);

    [DllImport("libc", SetLastError = true)]
    private static extern int madvise(IntPtr addr, nuint length, int advice);
}
