using System.Runtime.InteropServices;

namespace TopSecret;

/// <summary>
/// Cross-platform wrapper around the OS primitives that harden a page range
/// against leaking secrets into out-of-process artifacts:
/// <list type="bullet">
///   <item><b>Crash-dump exclusion</b> — <c>WerRegisterExcludedMemoryBlock</c> /
///   <c>WerUnregisterExcludedMemoryBlock</c> on Windows,
///   <c>madvise(MADV_DONTDUMP)</c> / <c>madvise(MADV_DODUMP)</c> on
///   Linux/Android. Excluded ranges are omitted from the dumps those
///   facilities produce (<see cref="TryExclude{T}"/> / <see cref="TryInclude{T}"/>
///   and the <c>…Range</c> forms).</item>
///   <item><b>Fork hardening</b> — <c>madvise(MADV_WIPEONFORK)</c> on
///   Linux/Android (4.14+), so a forked child reads zeros in place of the
///   secret (<see cref="TryWipeOnForkRange"/>).</item>
/// </list>
/// Both are best-effort <c>madvise</c>/WER advice on the same page-granular
/// substrate, so they share this wrapper's page-rounding and probe scaffolding.
/// </summary>
/// <remarks>
/// <para>
/// <b>What exclusion covers — and what it does not.</b> On Windows,
/// registration affects only dumps generated by Windows Error Reporting
/// (crash dumps, <c>WerReportAddDump</c>); Task Manager dumps, ProcDump,
/// debugger <c>.dump</c>, and kernel dumps still contain the bytes. On
/// Linux/Android, <c>MADV_DONTDUMP</c> affects only the kernel's core-dump
/// path; <c>ptrace</c> readers (gcore, debuggers) still see the pages. On
/// macOS, iOS, Mac Catalyst, and browser-wasm no exclusion primitive exists;
/// calls are silent no-ops there (see <see cref="IsSupported"/>). Dump
/// exclusion is therefore a best-effort layer on top of the encrypt-at-rest
/// and wipe-on-exit guarantees, not a substitute for them.
/// </para>
/// <para>
/// <b>Windows budget.</b> WER caps the number of registered blocks
/// (register + exclude combined) at 512 per process. Sensitive buffers are
/// transient — plaintext scratch lives for one operation, build buffers until
/// commit — so typical live registrations stay in the single digits, but a
/// process holding hundreds of concurrent sensitive buffers can exhaust the
/// budget; later <see cref="TryExclude{T}"/> calls then fail and the
/// configured <see cref="ProtectedStringOptions.MemoryLockingFailureBehavior"/>
/// applies at the call site.
/// </para>
/// <para>
/// <b>Page granularity (libc targets).</b> <c>madvise</c> operates on whole
/// pages, and the requested range is page-rounded here. A pinned-object-heap
/// page can hold unrelated objects, which then drop out of core dumps too
/// (harmless for security, mildly annoying for diagnostics). Exclusion is
/// one-way on libc targets — see <see cref="TryInclude{T}"/> for why wiped
/// pages deliberately stay excluded — so a live excluded buffer can never
/// lose its exclusion to a neighbour's teardown. Hot per-operation scratch
/// additionally rents from <see cref="LockedScratchPool"/>, whose slabs are
/// excluded once at creation.
/// </para>
/// </remarks>
internal static class DumpExclusion
{
    private const int MADV_DONTDUMP = 16;
    private const int MADV_DODUMP = 17;
    private const int MADV_WIPEONFORK = 18;
    private const int MADV_KEEPONFORK = 19;

    private static readonly Lazy<bool> s_supported =
        new(Probe, LazyThreadSafetyMode.ExecutionAndPublication);

    private static readonly Lazy<bool> s_wipeOnForkSupported =
        new(ProbeWipeOnFork, LazyThreadSafetyMode.ExecutionAndPublication);

    /// <summary>
    /// Whether a dump-exclusion primitive is reachable on this platform.
    /// <see langword="false"/> on macOS / iOS / Mac Catalyst / browser-wasm
    /// (no primitive exists), or when the probe call failed. The probe runs
    /// at most once per process.
    /// </summary>
    public static bool IsSupported => s_supported.Value;

    /// <summary>
    /// Attempts to exclude <paramref name="buffer"/> from OS-generated crash
    /// dumps. Returns <see langword="true"/> on success, for an empty buffer,
    /// or when the platform has no exclusion primitive (not-applicable is not
    /// a failure — the caller cannot act on it and the configured policy
    /// should not fire for a capability the OS simply does not offer).
    /// Returns <see langword="false"/> only when the platform primitive
    /// exists and the call failed (e.g. WER's 512-entry budget is exhausted),
    /// so the caller can apply
    /// <see cref="ProtectedStringOptions.MemoryLockingFailureBehavior"/>.
    /// </summary>
    /// <remarks>
    /// <paramref name="buffer"/> must already be pinned (e.g., allocated via
    /// <see cref="GC.AllocateArray{T}(int, bool)"/> with <c>pinned: true</c>).
    /// </remarks>
    public static bool TryExclude<T>(T[] buffer) where T : unmanaged
    {
        if (buffer.Length == 0) return true;
        return TryExcludeRange(
            Marshal.UnsafeAddrOfPinnedArrayElement(buffer, 0), checked((int)ByteSize(buffer)));
    }

    /// <summary>
    /// Reverses a prior <see cref="TryExclude{T}"/> on Windows, returning the
    /// WER budget entry. On libc targets this is a deliberate no-op:
    /// exclusion is one-way there.
    /// </summary>
    /// <remarks>
    /// WER registrations are exact-range, so unregistering one buffer cannot
    /// touch a neighbour. <c>madvise(MADV_DODUMP)</c> is page-granular: a
    /// wiped transient buffer's re-inclusion would strip
    /// <c>MADV_DONTDUMP</c> from any still-live excluded buffer sharing the
    /// page — e.g. a wrap key allocated next to its own per-operation
    /// ephemerals loses its exclusion after the first unwrap, permanently.
    /// Leaving wiped pages excluded is the conservative direction for a
    /// security library (the cost is that core dumps omit whatever the POH
    /// later reuses those pages for). Safe to call for buffers that were
    /// never excluded; failures are not actionable and are swallowed.
    /// </remarks>
    public static void TryInclude<T>(T[] buffer) where T : unmanaged
    {
        if (buffer.Length == 0) return;
        TryIncludeRange(
            Marshal.UnsafeAddrOfPinnedArrayElement(buffer, 0), checked((int)ByteSize(buffer)));
    }

    /// <summary>
    /// Excludes an arbitrary (caller-aligned) address range. Used by
    /// <see cref="LockedScratchPool"/> for a slab's page-aligned interior.
    /// Same return contract as <see cref="TryExclude{T}"/>.
    /// </summary>
    public static bool TryExcludeRange(IntPtr addr, int size)
    {
        if (size == 0) return true;
        if (!IsSupported) return true;
        return TryAdvise(addr, (nuint)size, exclude: true);
    }

    /// <summary>
    /// Reverses a prior <see cref="TryExcludeRange"/> on Windows (returning the
    /// WER budget entry); a deliberate no-op on libc targets, matching
    /// <see cref="TryInclude{T}"/>. For range owners that free the underlying
    /// memory immediately after.
    /// </summary>
    public static void TryIncludeRange(IntPtr addr, int size)
    {
        if (size == 0 || !IsSupported) return;
        if (!OperatingSystem.IsWindows()) return;
        TryAdvise(addr, (nuint)size, exclude: false);
    }

    /// <summary>
    /// Whether <c>madvise(MADV_WIPEONFORK)</c> is available (Linux/Android,
    /// kernel 4.14+). Probed once per process.
    /// </summary>
    public static bool IsWipeOnForkSupported => s_wipeOnForkSupported.Value;

    /// <summary>
    /// Marks a page-aligned, whole-page range so that after a <c>fork()</c> the
    /// <b>child</b>'s copy of the range reads as zeros — a defence-in-depth
    /// measure so secrets do not silently survive into a forked child (native
    /// interop, <c>fork</c>-based tooling). Linux/Android only, best-effort and
    /// silent: a pre-4.14 kernel or an unsupported host is a no-op, not a
    /// policy failure.
    /// </summary>
    /// <remarks>
    /// <b>Apply only to dedicated, secret-only, process-lifetime regions</b> —
    /// the <see cref="LockedScratchPool"/> slabs and the guarded master page.
    /// Because the advice is page-granular and persists on the mapping,
    /// setting it on a recyclable managed (POH) buffer would zero whatever the
    /// GC later places there in a forked child; the callers here own their
    /// pages outright and never recycle them to non-secret use.
    /// </remarks>
    public static bool TryWipeOnForkRange(IntPtr addr, int size)
    {
        if (size == 0 || !IsWipeOnForkSupported) return true;
        try { return Madvise(addr, (nuint)size, MADV_WIPEONFORK) == 0; }
        catch { return false; }
    }

    private static bool ProbeWipeOnFork()
    {
        if (!OperatingSystem.IsLinux() && !OperatingSystem.IsAndroid()) return false;
        return ProbePinned(Environment.SystemPageSize, static (addr, size) =>
        {
            if (Madvise(addr, size, MADV_WIPEONFORK) != 0) return false;
            // Reset the probe page's advice so this transient POH page does not
            // carry WIPEONFORK once it is recycled.
            Madvise(addr, size, MADV_KEEPONFORK);
            return true;
        });
    }

    private static nuint ByteSize<T>(T[] buffer) where T : unmanaged =>
        MemoryLocker.ByteSize(buffer);

    private static bool Probe()
    {
        // MADV_DONTDUMP/MADV_DODUMP are Linux-kernel advice values (3.4+);
        // the same numbers on other kernels mean something else or nothing,
        // and WerRegisterExcludedMemoryBlock exists only on Windows 10 /
        // Server 2016+ — so gate on the platforms explicitly rather than
        // letting the probe discover "support" by accident. macOS / iOS /
        // Mac Catalyst / browser-wasm have no primitive at all.
        if (!OperatingSystem.IsWindows() &&
            !OperatingSystem.IsLinux() &&
            !OperatingSystem.IsAndroid())
        {
            return false;
        }

        // TryAdvise owns the per-platform dispatch and the exception swallowing
        // (DllNotFoundException / EntryPointNotFoundException on old hosts
        // become false) — the probe just exercises a full round trip.
        return ProbePinned(64, static (addr, size) =>
        {
            if (!TryAdvise(addr, size, exclude: true)) return false;
            TryAdvise(addr, size, exclude: false);
            return true;
        });
    }

    /// <summary>
    /// Allocates a pinned probe buffer and runs <paramref name="roundTrip"/>
    /// against it, funnelling any platform-resolution exception to
    /// <see langword="false"/> so a probe can never crash the type initializer.
    /// Shared by <see cref="Probe"/> and <see cref="ProbeWipeOnFork"/>.
    /// </summary>
    private static bool ProbePinned(int size, Func<IntPtr, nuint, bool> roundTrip)
    {
        try
        {
            var probe = GC.AllocateArray<byte>(size, pinned: true);
            var addr = Marshal.UnsafeAddrOfPinnedArrayElement(probe, 0);
            return roundTrip(addr, (nuint)probe.Length);
        }
        catch
        {
            return false;
        }
    }

    private static bool TryAdvise(IntPtr addr, nuint size, bool exclude)
    {
        try
        {
            if (OperatingSystem.IsWindows())
            {
                if (exclude)
                {
                    return WerRegisterExcludedMemoryBlock(addr, (uint)size) == 0;
                }
                // Not-registered is indistinguishable from success for our
                // purposes (the entry is gone either way).
                WerUnregisterExcludedMemoryBlock(addr);
                return true;
            }

            return Madvise(addr, size, exclude ? MADV_DONTDUMP : MADV_DODUMP) == 0;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// <c>madvise</c> demands a page-aligned start address, so round the range
    /// out to page boundaries. See the type remarks for the page-granularity
    /// consequences of advising more than exactly the buffer's bytes.
    /// </summary>
    private static int Madvise(IntPtr addr, nuint size, int advice)
    {
        long page = Environment.SystemPageSize;
        long start = addr.ToInt64() & ~(page - 1);
        long end = (addr.ToInt64() + (long)size + page - 1) & ~(page - 1);
        return madvise((IntPtr)start, (nuint)(end - start), advice);
    }

    [DllImport("kernel32", ExactSpelling = true)]
    private static extern int WerRegisterExcludedMemoryBlock(IntPtr address, uint size);

    [DllImport("kernel32", ExactSpelling = true)]
    private static extern int WerUnregisterExcludedMemoryBlock(IntPtr address);

    [DllImport("libc", SetLastError = true)]
    private static extern int madvise(IntPtr addr, nuint length, int advice);
}
